name: Build and Release Fabric Mod

on:
  push:
    branches: [ "main" ]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: gradle build

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ steps.date.outputs.date }}
          name: Build ${{ steps.date.outputs.date }}
          files: build/libs/*.jar
          draft: false
          prerelease: true
